import * as PlexIcons from '@plexui/ui/components/Icon';
import type { CatalogIcon, IconCatalog, IconComponent } from '../types';

/**
 * Loader for the Plex Icons catalog.
 *
 * The icon set itself comes in via React-component imports from
 * `@plexui/ui/components/Icon` — every icon is already JSX, no SVG
 * string parsing needed. Tags, however, aren't shipped with the
 * package (the OpenAI Apps SDK source these are derived from doesn't
 * have a tag file either), so we fetch a side-car JSON generated by
 * `scripts/generate-plex-tags.mjs` and merge it onto the icon list.
 *
 * Cached at module scope.
 */
let cached: IconCatalog | null = null;

export async function loadPlexCatalog(): Promise<IconCatalog> {
  if (cached) return cached;

  // Tags are best-effort. If the JSON is missing or fails to parse the
  // catalog still loads (just without tags) — the build step that
  // copies the file is not in the dev-server hot-path and may not have
  // run on first dev start.
  let tagsByName: Record<string, string[]> = {};
  try {
    const response = await fetch('/icon-libraries/plex-tags.json');
    if (response.ok) {
      tagsByName = (await response.json()) as Record<string, string[]>;
    }
  } catch {
    // ignore — proceed without tags
  }

  // Filter out backward-compat aliases. Every primary Plex icon ships
  // with `Component.displayName === "<exportName>"` (set inline in each
  // svg/<Name>.tsx file). Aliases in packages/ui/src/components/Icon/
  // aliases.ts re-export the SAME default function under a different
  // export key — so the alias's `displayName` still equals the
  // CANONICAL name, not the alias key. Keeping only entries where
  // `displayName === key` drops every alias automatically (no
  // hand-curated blacklist to keep in sync).
  const icons: CatalogIcon[] = Object.entries(PlexIcons)
    .filter(([key, value]) => {
      if (typeof value !== 'function') return false;
      if (!/^[A-Z]/.test(key)) return false;
      const displayName = (value as { displayName?: string }).displayName;
      // Allow components without a displayName (treated as canonical)
      // and only drop entries where displayName explicitly disagrees
      // with the export key — that's the alias signature.
      return !displayName || displayName === key;
    })
    .map(([name, Component]) => {
      const tags = tagsByName[name];
      return {
        name,
        Component: Component as IconComponent,
        ...(tags && tags.length > 0 ? { tags } : {}),
      };
    })
    .sort((a, b) => a.name.localeCompare(b.name));

  cached = {
    id: 'plex',
    label: 'Plex Icons',
    buildImport: (name) => `import { ${name} } from '@plexui/ui/components/Icon';`,
    buildJsx: (name) => `<${name} />`,
    icons,
  };
  return cached;
}
