import type * as PageTree from 'fumadocs-core/page-tree';
import type { ReactNode } from 'react';

export interface DocsSectionNavItem {
  slug: string;
  label: string;
  href: string;
  matchSlugs?: string[];
}

const DOCS_SECTION_SLUGS = [
  'foundations',
  'concepts',
  'hooks',
  'transitions',
  'installation',
  'skills',
  'ai-setup',
  'mcp',
  'registry',
  'changelog',
] as const;

const NAV_ORDER = ['docs', 'components'] as const;

interface SectionFolder {
  slug: string;
  folder: PageTree.Folder;
  firstUrl: string;
}

function isFolder(node: PageTree.Node): node is PageTree.Folder {
  return node.type === 'folder';
}

function cloneNode(node: PageTree.Node): PageTree.Node {
  if (node.type === 'folder') {
    return {
      ...node,
      index: node.index ? { ...node.index } : undefined,
      children: node.children.map(cloneNode),
    };
  }

  if (node.type === 'page') {
    return { ...node };
  }

  return { ...node };
}

function cloneRoot(root: PageTree.Root): PageTree.Root {
  return {
    ...root,
    children: root.children.map(cloneNode),
    fallback: root.fallback ? cloneRoot(root.fallback) : undefined,
  };
}

function toLabel(value: ReactNode, fallback: string): string {
  if (typeof value === 'string') return value;
  if (typeof value === 'number') return String(value);
  return fallback;
}

function sectionSlugFromUrl(url: string): string | null {
  if (!url.startsWith('/')) return null;

  const parts = url.split('/').filter(Boolean);
  const docsIndex = parts.indexOf('docs');
  if (docsIndex === -1) return null;

  return parts[docsIndex + 1] ?? null;
}

function firstPageUrl(nodes: PageTree.Node[]): string | null {
  for (const node of nodes) {
    if (node.type === 'page') return node.url;
    if (node.type === 'folder') {
      if (node.index) return node.index.url;
      const nested = firstPageUrl(node.children);
      if (nested) return nested;
    }
  }

  return null;
}

function flattenFolderPages(folder: PageTree.Folder): PageTree.Item[] {
  const output: PageTree.Item[] = [];
  const seen = new Set<string>();

  const addItem = (item: PageTree.Item) => {
    if (seen.has(item.url)) return;
    seen.add(item.url);
    output.push({ ...item });
  };

  const walk = (nodes: PageTree.Node[]) => {
    for (const node of nodes) {
      if (node.type === 'page') addItem(node);
      if (node.type === 'folder') {
        if (node.index) addItem(node.index);
        walk(node.children);
      }
    }
  };

  if (folder.index) addItem(folder.index);
  walk(folder.children);

  return output;
}

function getSectionFolders(root: PageTree.Root): SectionFolder[] {
  const folders: SectionFolder[] = [];

  for (const node of root.children) {
    if (!isFolder(node)) continue;

    const firstUrl = node.index?.url ?? firstPageUrl(node.children);
    const slug = firstUrl ? sectionSlugFromUrl(firstUrl) : null;
    if (!slug || !firstUrl) continue;

    folders.push({ slug, folder: node, firstUrl });
  }

  return folders;
}

function navOrder(slug: string): number {
  const index = NAV_ORDER.indexOf(slug as (typeof NAV_ORDER)[number]);
  return index === -1 ? Number.MAX_SAFE_INTEGER : index;
}

/**
 * Hand-curated sidebar groups. URLs are hardcoded so the list stays
 * stable regardless of how Fumadocs flattens `meta.json`-rooted
 * folders inside `source.pageTree`.
 *
 * Layout (top to bottom of the sidebar):
 *
 *   ─ Get Started ─       3 entry points
 *   ─ Foundations ─       design tokens, colors, typography + dark mode + responsive
 *   ─ AI & Distribution ─ everything related to integrating Plex UI into AI tooling
 *                         and shipping Plex UI to consumers
 *   ─ API ─               runtime utilities (hooks, transitions)
 *   ─ Icons ─             autogenerated by buildIconsList
 *   ─ Components ─        autogenerated by buildComponentsList
 *
 * Folder index pages (/docs/foundations, /docs/concepts) are omitted on
 * purpose — their job was to list children, and the sidebar already
 * does that. Direct links still 200, just no sidebar entry.
 */

export type SidebarEntry = { label: string; url: string };

export type DocsGroup = {
  /** Stable identifier — used as a key by consumers picking specific groups. */
  id: string;
  /** Title shown above the entries (in the sidebar separator and in
   *  any presentational use like the /docs intro cards). */
  label: string;
  /** Short tagline describing what the group covers — used by the
   *  /docs intro cards under the title. Not shown in the sidebar. */
  description: string;
  entries: SidebarEntry[];
};

export const GET_STARTED: DocsGroup = {
  id: 'get-started',
  label: 'Get Started',
  description: 'Install the package, browse the changelog, and set up your project.',
  entries: [
    { label: 'Introduction', url: '/docs' },
    { label: 'Installation', url: '/docs/installation' },
    { label: 'Changelog', url: '/docs/changelog' },
  ],
};

export const FOUNDATIONS: DocsGroup = {
  id: 'foundations',
  label: 'Foundations',
  description:
    'Design tokens, color palettes, typography scale, and theming concepts.',
  entries: [
    { label: 'Design Tokens', url: '/docs/foundations/design-tokens' },
    { label: 'Colors', url: '/docs/foundations/colors' },
    { label: 'Typography', url: '/docs/foundations/typography' },
    // Dark Mode + Responsive Design both live as anchored sections on
    // a single /docs/concepts page (the per-anchor URLs all 307 there
    // anyway — see getSectionRedirect in app/docs/[[...slug]]/page.tsx),
    // so the sidebar exposes them as one entry that lands on the page.
    { label: 'Concepts', url: '/docs/concepts' },
  ],
};

export const AI_DISTRIBUTION: DocsGroup = {
  id: 'ai-distribution',
  label: 'AI & Distribution',
  description:
    'Plug Plex UI into Claude, MCP, Cursor, and ship via the Shadcn registry.',
  entries: [
    { label: 'AI Setup', url: '/docs/ai-setup' },
    { label: 'MCP Server', url: '/docs/mcp' },
    { label: 'Skills', url: '/docs/skills' },
    { label: 'Shadcn Registry', url: '/docs/registry' },
  ],
};

export const API: DocsGroup = {
  id: 'api',
  label: 'API',
  description: 'Runtime utilities — hooks for state and motion primitives.',
  entries: [
    { label: 'Hooks', url: '/docs/hooks' },
    { label: 'Transitions', url: '/docs/transitions' },
  ],
};

/** Curated groups in the order they appear in the sidebar. Components
 *  and Icons are autogenerated from `content/docs/{components,icons}/`
 *  and live as separate sidebar separators outside this list. */
export const DOCS_GROUPS: DocsGroup[] = [
  GET_STARTED,
  FOUNDATIONS,
  AI_DISTRIBUTION,
  API,
];

function toSidebarItems(entries: SidebarEntry[]): PageTree.Item[] {
  return entries.map((entry) => ({
    type: 'page',
    name: entry.label,
    url: entry.url,
  }));
}

const COMPONENTS_INDEX_URL = '/docs/components';
const ICONS_INDEX_URL = '/docs/icons';

function buildComponentsList(componentsSection: SectionFolder): PageTree.Item[] {
  // Hardcoded URL filter — fumadocs marks the folder as `root: true` in
  // meta.json and the resulting `folder.index` is not always set, so
  // comparing against `folder.index?.url` lets the index slip through.
  const all = flattenFolderPages(componentsSection.folder).filter(
    (page) => page.url !== COMPONENTS_INDEX_URL
  );
  return all.sort((a, b) =>
    toLabel(a.name, '').localeCompare(toLabel(b.name, ''))
  );
}

function buildIconsList(iconsSection: SectionFolder): PageTree.Item[] {
  // Mirrors `buildComponentsList` — expose the 6 library pages as a
  // separate sidebar group under their own "Icons" separator. The
  // grid index (/docs/icons) is intentionally dropped here: it already
  // appears under "Sections" as the entry-point link, and listing it
  // twice would create a duplicate row in the sidebar.
  //
  // Order is preserved from `content/docs/icons/meta.json` (Plex first
  // as the brand-bundled set, then external libraries) — unlike
  // components, alphabetic order here would bury Plex below Hugeicons.
  return flattenFolderPages(iconsSection.folder).filter(
    (page) => page.url !== ICONS_INDEX_URL
  );
}

/**
 * Reshapes the docs page tree into a categorized shadcn/ui-style
 * sidebar with six labeled groups. The original folder hierarchy
 * stays in `content/docs/` for routing — we just flatten it for
 * sidebar display.
 *
 * Group order: Get Started → Foundations → AI & Distribution → API →
 *              Icons → Components.
 *
 * Get Started / Foundations / AI & Distribution / API are
 * hand-curated lists (see SidebarEntry constants above). Icons and
 * Components are autogenerated from `content/docs/{icons,components}/`
 * because their content varies — Components has ~40 entries.
 */
function processRoot(root: PageTree.Root) {
  const sectionFolders = getSectionFolders(root);
  const componentsSection = sectionFolders.find((entry) => entry.slug === 'components');
  const iconsSection = sectionFolders.find((entry) => entry.slug === 'icons');

  const iconsList = iconsSection ? buildIconsList(iconsSection) : [];
  const componentsList = componentsSection ? buildComponentsList(componentsSection) : [];

  const nextChildren: PageTree.Node[] = [];

  for (const group of DOCS_GROUPS) {
    nextChildren.push({ type: 'separator', name: group.label });
    nextChildren.push(...toSidebarItems(group.entries));
  }

  if (iconsList.length > 0) {
    nextChildren.push({ type: 'separator', name: 'Icons' });
    nextChildren.push(...iconsList);
  }

  if (componentsList.length > 0) {
    nextChildren.push({ type: 'separator', name: 'Components' });
    nextChildren.push(...componentsList);
  }

  root.children = nextChildren;

  // Sections array drives the top-nav ("Components" label + active state).
  // The `Docs` entry's matchSlugs covers everything except components/icons
  // so the top-nav `Docs` link stays inactive on /docs/components and /docs/icons.
  const sections: DocsSectionNavItem[] = [];

  const docsHref = '/docs';

  sections.push({
    slug: 'docs',
    label: 'Docs',
    href: docsHref,
    matchSlugs: [...DOCS_SECTION_SLUGS],
  });

  if (componentsSection) {
    sections.push({
      slug: 'components',
      label: toLabel(componentsSection.folder.name, 'Components'),
      href: componentsSection.folder.index?.url ?? componentsSection.firstUrl,
      matchSlugs: ['components'],
    });
  }

  return sections.sort((a, b) => {
    const orderA = navOrder(a.slug);
    const orderB = navOrder(b.slug);

    if (orderA !== orderB) return orderA - orderB;
    return a.label.localeCompare(b.label);
  });
}

export function buildDocsTreeNavigation(tree: PageTree.Root): {
  tree: PageTree.Root;
  sections: DocsSectionNavItem[];
} {
  const cloned = cloneRoot(tree);
  const sections = processRoot(cloned);

  if (cloned.fallback) processRoot(cloned.fallback);

  return {
    tree: cloned,
    sections,
  };
}
