import type { ComponentType, SVGProps } from 'react';

export type IconComponent = ComponentType<SVGProps<SVGSVGElement>>;

/**
 * One catalog entry — either a React component (Plex Icons, where each
 * icon already lives as a JSX export) or a raw SVG string (external
 * libraries fetched as a static JSON catalog so we don't bundle 1.9k
 * React components into the docs route).
 */
export type CatalogIcon = (
  | { name: string; Component: IconComponent; svg?: undefined }
  | { name: string; Component?: undefined; svg: string }
) & {
  /** Aliases / search tags. Lucide ships these via `tags.json`; other
   *  catalogs may omit. Surfaced in the detail panel below the name. */
  tags?: string[];
  /** Filled-outline geometry of the same icon, generated by
   *  `scripts/build-lucide-outlined.mjs`. Currently populated only for
   *  Lucide. When present, the detail panel exposes an "Outlined" toggle
   *  that swaps the preview + copy-actions to use this version instead.
   *  Tile rendering always uses the primary `svg` (or `Component`). */
  outlinedSvg?: string;
};

/** Options the detail panel passes to a catalog's snippet builders so
 *  Copy import / Copy JSX reflect the current panel state — the chosen
 *  stroke width and the Outlined toggle. Both fields are optional;
 *  catalogs may ignore either or both. */
export type IconBuildOptions = {
  /** Selected stroke width. Builders should emit a prop only when this
   *  differs from the library's default (typically 2). */
  strokeWidth?: number;
  /** True when the user flipped the "Outlined" toggle in the panel. Only
   *  meaningful for catalogs that ship an `outlinedSvg` companion. */
  outlined?: boolean;
};

export type IconCatalog = {
  /** Library identifier. Should match the `library` prop on <IconBrowser>. */
  id: string;
  /** Human-readable name shown in the dialog header. */
  label: string;
  /** Builds the `Copy import` snippet for a single icon name. */
  buildImport: (name: string, opts?: IconBuildOptions) => string;
  /** Builds the `Copy JSX` snippet (one-liner usage). */
  buildJsx: (name: string, opts?: IconBuildOptions) => string;
  /** All icons. Pre-sorted alphabetically. */
  icons: CatalogIcon[];
};
